start-credits: 1000 # Credits given to new users.

# Credit cost per API request.
costs:
  other: 5 # Other endpoints

  chat-models: # chat completions
    gpt-4-32k: 100
    gpt-4: 20
    gpt-3: 5

## Roles Explanation

# Bonuses: They are a multiplier for costs
#          They work like: final_cost = cost * bonus

roles:
  owner:
    bonus: 0
  enterprise:
    bonus: 0.2
  admin:
    bonus: 0.4
  helper:
    bonus: 0.6
  default:
    bonus: 1.0
